### ISSUE TITLE
App Crash when access to settings

### ISSUE THREAD

**Issue by Beomi** [taggon/highlight#10]
OS: OS X El Capitan 10.11.6
Device: iMac(27", Late 2013)

App Crash when I access to settings with os notice bar.

상단바에서 '환경설정' 진입시 앱이 꺼집니다.

**Comment by taggon** [comment]
Can you check if this problem still exists in the latest version?
최신 버전에서도 문제가 계속 발생하는지 확인부탁드려도 될까요?

**Comment by taggon** [comment]
This issue is closed as the reporter has not responded for a long time.
오랫동안 응답이 없어서 일단 닫겠습니다.
