### ISSUE TITLE
앱종료 현상

### ISSUE THREAD

**Issue by nyxchung** [taggon/highlight#2]
코드의 종류와 무관하게 구문복사를 선택하면 앱이 종료됩니다. 제가 소유한 iMac, Macbook Pro 두 대 모두 재현됩니다. (시에라10.12.3)
(구문복사 외에도 환경설정에서 스타일 탭을 누르면 앱이 종료 됩니다)

**Comment by taggon** [comment]
Can you check if this problem still exists in the latest version?
최신 버전에서도 문제가 계속 발생하는지 확인부탁드려도 될까요?

**Comment by nyxchung** [comment]
잘 동작하네요! 고맙습니다!
