### ISSUE TITLE
App Crash on call Shortcut

### ISSUE THREAD

**Issue by Beomi** [taggon/highlight#9]
App Crashed right after call highlight with shortcut.

MacOS Sierra 10.12.6
Macbook 12" (2016)
Highlight 1.4.1 (Latest)

Hightlight앱에 단축키를 등록하고 코드 복사 후 단축키로 실행시 앱이 꺼집니다.

**Comment by taggon** [comment]
This bug is fixed in v1.4.3. Thanks for reporting this!
v1.4.3 버전에서 관련 문제를 수정했습니다. 감사합니다.

**Comment by Beomi** [comment]
```
MacOS Sierra 10.12.6
iMac (27-inch, Late 2013)
Highlight 1.4.3 (Latest)
```

확인했습니다. 감사합니다 👍
